---
driver:
  name: digitalocean
  ssh_timeout: 15
  ssh_retries: 5

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[openssh::default]
    attributes:
