language: ruby
cache:
- bundler: true
- apt: false
gemfile:
- Gemfile
rvm:
- 1.9.3
script: bundle exec strainer test openssh apt iptables
env:
  global:
  - secure: eAq120w5+eBJvQpDnHawZ8IJX191K9nNOAkxruMFNc9lNIGzKmBa+lycIyWonPhAWl7QA3qJB125nLBZtsPO60Sf4E9WDxFx2R2Oh2KOYYKwyDmCZPegk8u4ebNLuKpH+4rrGfI8TzOApmysM20Sz1t1cXNpBXuoD5/dm3+kdhY=
  - secure: aYQASZDIV6/cb8wp8u4ctENKHC4F8gCGY38u3GZoQXigwsVXIIpv9z87sfPx1xvDtMdZE+hx/1oZgDnvjBCHBiHDQxACpFcOJxuuUUmY2au6ctKZtRm+5o/FV1hSYIxAKo9H1eLuPC3epV0YXGDB8CdY5XABwbVrn93E67ShTu4=
  - secure: KlX7l9UyGF1nmib6c7nRu7XlJxdkryOa740oKoo63iUJU/kbGJzaD2VIl1QHfTNSIbSYqRIccX8+ESnMfeXCcddCYdAu4FRbB8L2ZKNvm/IDICL4Oa03h1SwZBpaePIbA75sZ81oZiK003ht12iM6PyHwMdnXq/gY6F5/vmkkFM=
