language: ruby
cache:
- bundler: true
- apt: false
gemfile:
- Gemfile
rvm:
- 1.9.3
script: bundle exec strainer test openssh apt iptables
env:
  global:
  - secure: Ee8//mLdnYo9JaOIxWthBPAuTBLYAoC77YwFZMqNpP66qURk32xr6BdaWGqRgUKGTOIyH/n7GFMdkZyRxwtbaDWU7k7s0OhYeHDcBIuugL0BJ1ThkAmO1Q7XO5YpnROIrf3fGXPBhLSxMkkWVMKw9FXqwIVipTBSoZLONp54pwg=
  - secure: JjtNQuf2t6g9JLDc2LUfFJWqXk8UumuVO3u1KgmYQ7ipXOgpowMzSVgikS6/pfA0ZMwfMrkjuFSvyAI8pGU9POavi6K1XKyLq+54QK2V+weEQhKqDJM7gVGvHtD1bdKd610Jz5FTAgsQQgPh0A0q8EUdfD0oWa8O4Y6eSKOyzP0=
  - secure: J1JZ40coh8DEpZesiuhYqrQmrW5+a/ODafKUuhrFbGfdoRddlDR9NEHne44BZkfoySvA+hPvl9i/TpVevfWzuvrn79h5iwNZGUixCTV2tszimnjKDSzZBHndpXdfjveSwnUkH5LoNMGJ4TI1au90FU5aBHFLsnVFS52uoKGkE0E=
