language: ruby
cache:
- bundler: true
- apt: false
gemfile:
- Gemfile
rvm:
- 1.9.3
script: bundle exec strainer test openssh apt iptables
env:
  global:
  - secure: KerMUNqg2pv/DwqoAJ1fHrSA+7PWLx038HTrNapbU+IlFVV55Tl8wZA9iQmkvZepWgrsaOylgVbkBp4kOHg3Pd4CzaYdGfJ/dptmgpSSwrntIGk0fIOyJPIF28PQvAbWCJvlFpMV5K6WAdItek7NZfV04HvO0pVFV4iPjbdEsmc=
  - secure: I5cgpd+eH7U1o4Cjk/yNdK0MDzpCvLz62pjAx4NhBM8HpEz9A20XhRCzp5Qpi7sw6bHo/FPZgUI4qVapjqubCC3NMrEcrx1cjKss3u5qUukvsrNOvaguiO/zHzX+kSjG1vs7KvHAw4xtKcxol12ecTywKyjj2l4mrLUtekN5usE=
  - secure: LvrwDAHn7/JcHFlvHFZSMhr7okuEc4NH6YtPAul456wO1GbwBkkPXyK6i8Pg6StOar5eX+PhnnIscFgCzN74deyKJqkr/v8cF8exJMhuk9xdyzh8dzEZi729JmbNmXRjfEh2KoVD6/2JJ8cMWRdQh/7E3x9Jgg+D/cVCOP8rNbg=
